### ISSUE TITLE
Feature request: display artist-song currently playing in on-hover tool tip

### ISSUE THREAD

**Issue by Alyust** [assen-totin/mate-applet-streamer#1]
At the moment thre is only radiostation title.
Artist name and song title would be realy nice to have.

Thank you so much for this realy usefull app!

**Comment by assen-totin** [comment]
Hi, vredda,

I'm glad you like the applet. 

It seems easier than I expected, at least on MATE where we use GStreamer 1.0. I'll probably have an updated version in the next few days.

**Comment by Alyust** [comment]
Wow, that's a great piece of news.
I use Fedora which updates its packages rapidly, so I don't expect it would take long to get the improved version.
Thank you!

**Comment by assen-totin** [comment]
Feature added as pop-up notification (can be turned off in the Options tab of the All Stations menu entry) and via the tooltip. 

Announcement and build instructions: http://forums.mate-desktop.org/viewtopic.php?f=16&t=1988&p=11207#p11207
