### ISSUE TITLE
Stream title pop-ups every few seconds

### ISSUE THREAD

**Issue by tarakbumba** [assen-totin/mate-applet-streamer#3]
I have build mate-applet-streamer and pushed to official Mageia repositories. But i have problem about notifications. If i check the "Show notifications with song titles"; notifications begin popping up every few (2 - 5) seconds and it gets annoying most of time. Expected behaviour is popping up when song/stream/radio station is changed.

Btw, this is a gtk2 build of the applet.

**Comment by tarakbumba** [comment]
Example screenshot. Notice that multiple notifications:

![screenshot at 2015-12-28 01 38 28](https://cloud.githubusercontent.com/assets/1156718/12012556/c0fe8d98-ad03-11e5-85f9-6dc463a9b92b.png)

**Comment by assen-totin** [comment]
Hi, Atilla!

Thanks for your report.

The notification pops up whenever the media stream contains a frame with the song title. Normally, this should only happen when the song title changes. This is exactly how it works on the Icecast stations I listen to (GTK2, GStreamer 1.0). 

Can you check your build with this stream: http://streaming210.radionomy.com:80/all-smooth-jazz ? Also, can you send me the URL of the stream that misbehaves? 

In addition, which version of GStreamer you have - 1.0 or 0.10? 

I'll add a check for change in the song title to protect users from faulty streams that send it too often. 

WWell,

Assen

**Comment by tarakbumba** [comment]
Thank you for fast response! I have compiled the applet with gstreamer 1.0. You can view rpm spec file at [Mageia svn](http://svnweb.mageia.org/packages/cauldron/mate-applet-streamer/current/SPECS/mate-applet-streamer.spec?revision=915540&view=co).
Your suggested [stream url](http://streaming210.radionomy.com:80/all-smooth-jazz) is OK. But not all icecast streams. For example Latina 95.1 FM stream from icecast list behaves just like my first comment. I' m attaching my personal streams list here (only Turkish radios) which almost all behaves same. Try Joy Türk stream url for example. Hope this helps.

Attachement:
[radyolar.xml.zip](https://github.com/assen-totin/mate-applet-streamer/files/73469/radyolar.xml.zip)

**Comment by assen-totin** [comment]
Hi,

Thanks for the links - yes., the Latina 95.1 FM does what I suspected, inserts the meta data frames too often. Here is a release of the applet which checks if the song title has changed and only pushes a notification if so: 
http://www.zavedil.com/wp-content/uploads/2015/12/mate-applet-streamer-0.3.3.tar.gz

Let me know if this fixes the issue for your other problematic stations too.

**Comment by tarakbumba** [comment]
Thank you for your quick fix. mate-applet-streamer-0.3.3 fixed this issue and i have encounter no regressions. :)
