### ISSUE TITLE
Applet right-click menu is not translatable?

### ISSUE THREAD

**Issue by tarakbumba** [assen-totin/mate-applet-streamer#4]
Hi. While mate-applet-streamer is fully translated in tr.po, right-click menu items are not translated. (Recent, Favorites, All Stations and About items). I' ve noticed that streamer.pot also doesn't contain these strings as translatable items. Is it possible to make these strings translatable and add streamer.pot?

**Comment by assen-totin** [comment]
Hi, Atilla,

I was expecting that GTK will take care of this via the GTK Stock Items we use, but it seems that with ActionGroup this is not true. 

Here is an updated version which should (hopefully) translate the menu entries via the standard PO file when using MATE. I took the liberty to fill-in the Turkish translation for "About", "Recent" and "All Stations", but, please, check it for me. 
http://www.zavedil.com/wp-content/uploads/2015/12/mate-applet-streamer-0.3.4.tar.gz

**Comment by tarakbumba** [comment]
Unfortunately version 0.3.4 still shows untranslated menu and it appears to me that you've forgotten add modified translation catalogs into [source archive](http://www.zavedil.com/wp-content/uploads/2015/12/mate-applet-streamer-0.3.4.tar.gz). But source archive from github releases includes modified gettext catalogs so i tried to build them but failed due to issue #5 :(

**Comment by assen-totin** [comment]
Hm, not exactly; the menu strings are defined in a header file and the "make dist" command was rebuilding the PO files without looking into this header. Should be fixed here:
http://www.zavedil.com/wp-content/uploads/2015/12/mate-applet-streamer-0.3.5.tar.gz

**Comment by tarakbumba** [comment]
Thank you. It is now all set. Just one thing that it should be "Tüm yayın istasyonları" not "Tüm istasyonları" in Turkish but not a big problem.
